### ISSUE TITLE
Why not synchronize when files are modified?

### ISSUE THREAD

**Issue by snfnwgi** [Cimpress-MCP/vagrant-winrm-syncedfolders#12]
Why not synchronize when files are modified

**Comment by chrisbaldauf** [comment]
@snfnwgi, this plugin was created to play nicely with the [Vagrant Managed Servers](https://github.com/tknerr/vagrant-managed-servers) plugin. You're free to propose alternate use cases or new feature, but since this plugin is no longer part of our primary deployment toolchain I'm disinclined to make changes.

**Comment by snfnwgi** [comment]
@chrisbaldauf Can I install this plugin to synchronize my catalog?
